my_app/urls.py
from django.urls import path
from . import views


app_name = 'my_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('rental_review/', views.rental_review, name='rental_review'),
    path('thank_you/', views.thank_you, name='thank_you'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('my_app/', include('my_app.urls')),
    path('admin/', admin.site.urls),
]

my_app/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator

# Create your models here.

class Review(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    stars = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])


class Car(models.Model):
    name = models.CharField(max_length=100)
    year = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

my_app/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm

# class Review(forms.Form):
#     first_name = forms.CharField(label='First Name', max_length=200)
#     last_name = forms.CharField(label='Last Name', max_length=200)
#     email = forms.EmailField(label="Email")
#     review = forms.CharField(label="Please write your review")

class Review(ModelForm):
    class Meta:
        model = Review
        fields ="__all__"

        labels = {
            'first_name':"First_name",
            'last_name':"Last Name",
            'stars':"Rating"
        }

my_app/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse
from .models import Car
from .forms import Review



def rental_review(request):
    if request.method == 'POST':
        form = Review(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('my_app:thank_you'))
    else:
        form = Review()
    return render(request, 'my_app/rental_review.html',context={'form':form})



def thank_you(request):
    return render(request, 'my_app/thank_you.html')





def index(request):
    objects = Car.objects.all()
 

    return render(request, 'my_app/index.html',context={'objects':objects})

def add(request):
    if request.POST:
        brand = request.POST['name']
        year = request.POST['year']
        Car.objects.create(name=brand, year = year)
        return redirect(reverse('my_app:index'))
        
 
    return render(request, 'my_app/add.html')

my_app/templates/my_app/add.html
{% extends 'base.html' %}


{% block content %}

    <h1>This is Add Page</h1>

    <form action="" method="post">
        {%csrf_token%}
        <div class="mb-3">
          <label for="Brand" class="form-label">Brand</label>
          <input type="text" class="form-control" id="name" name="name">
        
        </div>
        <div class="mb-3">
          <label for="year" class="form-label">Year</label>
          <input type="number" class="form-control" id="year" name="year">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

{% endblock content %}

my_app/templates/my_app/index.html
{% extends 'base.html' %}


{% block content %}

    <h1>This is Index Page</h1>
    {% for obj in objects %}
   <ul>
    <li> {{obj.name}} and  {{obj.year}}</li>
    
   </ul>
    {% endfor%}
{% endblock content %}

my_app/templates/my_app/rental_review.html
{% extends 'base.html' %}


{% block content %}

    <h1>This is Rental Review Page</h1>

    <form action="" method="post">
        {%csrf_token%}
        {% for field in form %}
        <div class="mb-3">
            {{field.label_tag}}
        </div>
        
        {{field}}
        {{field.errors}}
        
        {% endfor %}
        <input type="submit">

    </form>
{% endblock content %}

my_app/templates/my_app/thank_you.html
{% extends 'base.html' %}


{% block content %}

    <h1>Thank you Page</h1>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    
    <div class="container">

        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
        
                  <a class="nav-link" href="{% url 'my_app:index' %}">Index</a>
                  <a class="nav-link" href="{% url 'my_app:add' %}">Add</a>
                  <a class="nav-link" href="{% url 'my_app:rental_review' %}">Rental Review</a>
                  <a class="nav-link" href="{% url 'my_app:thank_you' %}">Thank You</a>
                </div>
              </div>
            </div>
          </nav>

        {% block content %}


        {% endblock content %}
    </div>

</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>